spring.application.name=meetingsum
spring.datasource.url=jdbc:postgresql://localhost:5433/meetingsum
spring.datasource.username= hkakashi
spring.datasource.password=123321
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false